### ISSUE TITLE
option for only code blocks, not inline?

### ISSUE THREAD

**Issue by ryanguill** [8bitgentleman/roam-depot-copy-code-block#2]
Thank you for the great extension! I've thought of doing this myself a few times but have never gotten to it. 

Would it be possible to get a setting to toggle so it would not show up on inline code references? I use inline code references a lot to talk about variables and other things that I wouldn't want to copy, just to get the style of the text to look different.

(also one more note, there is a typo in the roam depo description, `clock` instead of `block`: `Adds a button to copy the contents of a code clock to the clipboard`)

**Comment by 8bitgentleman** [comment]
Hmm I'll have to think on that, may have to restructure a bit but it should be possible

**Comment by ryanguill** [comment]
If you would be interested in a PR I could give it a shot.

**Comment by 8bitgentleman** [comment]
Would definitely welcome a pr! I'm thinking you'd probably have to put have a check for a new extensionAPI settings panel toggle within the mutationObserver

**Comment by 8bitgentleman** [comment]
closed via #3
