### ISSUE TITLE
Console error on copy, both inline and block

### ISSUE THREAD

**Issue by cori** [8bitgentleman/roam-depot-copy-code-block#5]
This morning I started seeing this error in the console in both Brave and Arc

```
1fe36c97-27ba-4932-8540-ebc57469db01:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '2')
    at HTMLSpanElement.i (1fe36c97-27ba-4932-8…ebc57469db01:2:9320)
```

(this is from inline - it changes to `reading '6'` when copying a block)

TBQH it's been a while since I've used the functionality, so I have no idea when this may have started.

OS: macOS Ventura 13.4
Arc: `Version 0.106.1 (39259) Chromium Engine Version 114.0.5735.45`
Brave: `[Version 1.52.117 Chromium: 114.0.5735.90 (Official Build) (arm64)](https://brave.com/latest/)`

I'll try on some other browser when I can.

**Comment by 8bitgentleman** [comment]
hmm I'll look into this, Does the extension still work for you?

**Comment by cori** [comment]
hey sorry for the delay - it does not. I see the same error in Safari as well.

**Comment by buildaworld** [comment]
It has been a long time.

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '2')
`

**Comment by 8bitgentleman** [comment]
Long enough I'd say, the fix for this has been submitted to Roam for review. You can follow the pull request [here](https://github.com/Roam-Research/roam-depot/pull/883)

**Comment by 8bitgentleman** [comment]
This fix is now live in Roam Depot!

**Comment by cori** [comment]
LGTM! Thanks so much!
