### ISSUE TITLE
Copy Button on Code Blocks and Inline Code Not Working

### ISSUE THREAD

**Issue by tatoyeba** [8bitgentleman/roam-depot-copy-code-block#6]
Hello,

I hope this message finds you well. I am reaching out to report an issue I've encountered with the copy button feature in your Roam Research extension. Here's a brief overview:

**Issue Description:**
While the copy buttons appear correctly on both code blocks and inline code segments, clicking these buttons does not actually copy the code content to the clipboard. This issue persists in both scenarios.

**Environment:**
- **OS**: MacOS Sonoma 14.5
- **Roam Version**: 0.11.5-ebe1cb0b (up-to-date as of June 10, 2023)
- **Application**: Roam Research App (Native)

**Troubleshooting Steps Tried:**
- Restarting MacOS
- Restarting Roam Research
- Reinstalling the extension

None of these steps have resolved the issue.

**Additional Context:**
I have been using your tools for a long time and have always appreciated the functionality they add to my workflow. Unfortunately, I am unsure when this issue first started occurring, but it was functioning correctly at least a year ago. I also have no reliable way to reproduce the issue under different conditions or setups.

Thank you for looking into this. Please let me know if you need any more information.

**Comment by 8bitgentleman** [comment]
Thanks for reaching out! The fix for this has actually already been submitted to Roam for review. You can follow the pull request [here](https://github.com/Roam-Research/roam-depot/pull/883)

**Comment by 8bitgentleman** [comment]
This fix is now live in Roam Depot!
